# Example configuration file
# Copy this to config/config.yaml and update with your settings

# API Settings
api:
  base_url: "https://community.shopify.dev"
  rate_limit: 1.0  # requests per second
  timeout: 30.0  # seconds
  max_retries: 3

# Database Settings
database:
  url: "sqlite:///data/database/forum.db"
  echo: false  # SQL logging

# Scraping Settings
scraping:
  batch_size: 100  # topics per batch
  checkpoint_interval: 10  # save checkpoint every N items
  checkpoint_dir: "data/checkpoints"
  
# Categories to scrape
categories:
  - id: 18
    name: "Webhooks and Events"
    slug: "webhooks-and-events"
    
# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/forum_analyzer.log"

# LLM Analysis Configuration
llm_analysis:
  api_key: ""  # Your Anthropic API key (get from https://console.anthropic.com)
  model: "claude-opus-4"
  batch_size: 10
  max_tokens: 4096
  temperature: 0.0
  theme_context_limit: 50  # Max topics to analyze for theme discovery
  context_char_limit: 15000 # Max characters for analysis context to avoid API errors
  
  # Ask command settings
  ask:
    context_limit: 50  # Max topics to include in context
    cache_queries: true